//@version=6
strategy("Stormer Forex - IFR2 + ADX + MMS20 + Tendência MMS200 (Alinhado)", overlay = true, margin_long = 100, margin_short = 100)

    // ---- PARÂMETROS DE ENTRADA ----
    ifr_length = input.int(2, title = "Período do IFR")
                     ifr_buy = input.int(25, title = "IFR Compra (Sobrevenda)")
                                   ifr_sell = input.int(75, title = "IFR Venda (Sobrecompra)")
                                                  mms_length = input.int(20, title = "Período da Média Móvel (Stop)")
                                                                   trend_length = input.int(200, title = "Média de Tendência Longa")

                                                                                  // Parâmetros do ADX
                                                                                  adx_len = input.int(14, title = "Período do ADX")
                                                                                                adx_max = input.int(30, title = "ADX Máximo para Entrar")

                                                                                                          // ---- CÁLCULO DOS INDICADORES ----
                                                                                                          rsi_value = ta.rsi(close, ifr_length)
                                                                                                                          mms_20 = ta.sma(close, mms_length)
                                                                                                                                       mms_200 = ta.sma(close, trend_length)

                                                                                                                                                     // Cálculo do ADX
                                                                                                                                                     [diPlus, diMinus, adx_value] = ta.dmi(adx_len, adx_len)

                                                                                                                                                                                    // ---- NOVOS FILTROS DE ALINHAMENTO DA MÉDIA DE STOP (MMS 20) ----
                                                                                                                                                                                    // Para Compra: O fechamento do candle anterior deve estar ACIMA da MMS 20 (Média abaixo dos candles)
                                                                                                                                                                                    media_abaixo_dos_candles = close[1] > mms_20[1]

                                                                                                                                                                                                               // Para Venda: O fechamento do candle anterior deve estar ABAIXO da MMS 20 (Média acima dos candles)
                                                                                                                                                                                                               media_acima_dos_candles = close[1]<mms_20[1]

                                                                                                                                                                                                                                                  // ---- CONDIÇÕES DE OPERAÇÃO ----
                                                                                                                                                                                                                                                  // COMPRA: Filtro 200 + IFR2 + ADX + Nova regra da MMS 20 abaixo do preço
                                                                                                                                                                                                                                                  buy_condition = close> mms_200 and rsi_value < ifr_buy and adx_value < adx_max and media_abaixo_dos_candles and strategy.position_size
                                                                                                                                                                                                                                         == 0

                                                                                                                                                                                                                                         // VENDA: Filtro 200 + IFR2 + ADX + Nova regra da MMS 20 acima do preço
                                                                                                                                                                                                                                         sell_condition = close < mms_200 and rsi_value > ifr_sell and adx_value<adx_max and media_acima_dos_candles and strategy.position_size == 0

                                                                                                                                                                                                                                                                                                                     // Alvos de Saída (Calculados no momento da entrada)
                                                                                                                                                                                                                                                                                                                     target_long = ta.highest(high, 2)
                                                                                                                                                                                                                                                                                                                                       target_short = ta.lowest(low, 2)

                                                                                                                                                                                                                                                                                                                                                      // Condições de Stop (Fechamento cruzando a MMS 20)
                                                                                                                                                                                                                                                                                                                                                      stop_long = close<mms_20
                                                                                                                                                                                                                                                                                                                                                                            stop_short = close>
                                                                                                                                                                                                                                                                                                                                                                      mms_20

                                                                                                                                                                                                                                                                                                                                                                  // ---- EXECUÇÃO DAS ORDENS ----
                                                                                                                                                                                                                                                                                                                                                                  if (buy_condition)
                                                                                                                                                                                                                                                                                                                                                                      strategy.entry("Compra", strategy.long)

                                                                                                                                                                                                                                                                                                                                                                          if (sell_condition)
                                                                                                                                                                                                                                                                                                                                                                              strategy.entry("Venda", strategy.short)

                                                                                                                                                                                                                                                                                                                                                                  // Gerenciamento Comprado
                                                                                                                                                                                                                                                                                                                                                                  if (strategy.position_size > 0)
                                                                                                                                                                                                                                                                                                                                                                      strategy.exit("Alvo Long", from_entry = "Compra", limit = target_long) if (stop_long)
                                                                                                                                                                                                                                                                                                                                                                          strategy.close("Compra", comment = "Stop MMS20 Long")

                                                                                                                                                                                                                                                                                                                                                                  // Gerenciamento Vendido
                                                                                                                                                                                                                                                                                                                                                                  if (strategy.position_size < 0)
                                                                                                                                                                                                                                                                                                                                                                      strategy.exit("Alvo Short", from_entry = "Venda", limit = target_short) if (stop_short)
                                                                                                                                                                                                                                                                                                                                                                          strategy.close("Venda", comment = "Stop MMS20 Short")

                                                                                                                                                                                                                                                                                                                                                                  // ---- LÓGICA DE COLORIR O FUNDO (APENAS RESULTADO) ----
                                                                                                                                                                                                                                                                                                                                                                  var int last_closed_count = 0 current_closed_count = strategy.closedtrades
                                                                                                                                                                                                                                                                                                                                                                                                                           trade_just_closed = current_closed_count> last_closed_count

                                                                                                                                                                                                                                                                                  color bg_color = na if (trade_just_closed) float last_trade_profit = strategy.closedtrades.profit(current_closed_count - 1) if (last_trade_profit > 0)
                                                                                                                                                                                                                                                                                                                                                           bg_color : = color.new(color.green, 75)                 // Verde para Lucro
                                                                                                                                                                                                                                                                                                                                                                        else bg_color : = color.new(color.red, 75) // Vermelho para Prejuízo

                                                                                                                                                                                                                                                                                                                                                                                          last_closed_count : = current_closed_count

                                                                                                                                                                                                                                                                                                                                                                                                              // ---- PLOTAGEM VISUAL ----
                                                                                                                                                                                                                                                                                                                                                                                                              plot(mms_20, color = color.blue, title = "MMS 20 (Stop)", linewidth = 1)
                                                                                                                                                                                                                                                                                                                                                                                                                  plot(mms_200, color = color.purple, title = "MMS 200 (Tendência)", linewidth = 3)

                                                                                                                                                                                                                                                                                                                                                                                                                      bgcolor(bg_color)
